FROM node:16-alpine as build
LABEL maintainer="Joan Font <joanfont@gmail.com>"
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

ADD package.json yarn.lock ./

RUN yarn install

ADD . .

RUN yarn build

FROM nginx:1.21-alpine

COPY --from=build /app/docs /usr/share/nginx/html

ADD docker/nginx/nginx.conf /etc/nginx/conf.d/default.conf